export const PACKAGE_DEFAULTS: Record<string, { label: string; priceINR: number; originalPriceINR: number }> = {
  'thailand-budget-trip':          { label: 'Thailand Budget Trip (5N)',          priceINR: 49499, originalPriceINR: 61999 },
  'bali-honeymoon-package':        { label: 'Bali Honeymoon Package (6N)',        priceINR: 52499, originalPriceINR: 65999 },
  'dubai-tour-package-from-delhi': { label: 'Dubai Tour Package from Delhi (5N)', priceINR: 36499, originalPriceINR: 46999 },
  'singapore-tour-package':        { label: 'Singapore Tour Package (4N)',        priceINR: 44999, originalPriceINR: 42999 },
  'maldives-luxury-package':       { label: 'Maldives Luxury Package (4N)',       priceINR: 89999, originalPriceINR: 115000 },
  'goa-tour-package':              { label: 'Goa Tour Package (3N)',              priceINR: 9999,  originalPriceINR: 13999 },
  'kashmir-tour-package':          { label: 'Kashmir Tour Package (5N)',          priceINR: 18999, originalPriceINR: 24999 },
  'kerala-tour-package':           { label: 'Kerala Tour Package (5N)',           priceINR: 15999, originalPriceINR: 21999 },
  'manali-tour-package':           { label: 'Manali Tour Package (4N)',           priceINR: 12999, originalPriceINR: 16999 },
  'himachal-tour-package':         { label: 'Himachal Pradesh Tour Package (5N)',  priceINR: 13999, originalPriceINR: 18999 },
  'uttarakhand-tour-package':      { label: 'Uttarakhand Tour Package (5N)',       priceINR: 11999, originalPriceINR: 15999 },
  'rajasthan-tour-package':        { label: 'Rajasthan Tour Package (6N)',         priceINR: 14999, originalPriceINR: 19999 },
  'andaman-tour-package':          { label: 'Andaman Tour Package (4N)',           priceINR: 24999, originalPriceINR: 32999 },
  'ladakh-tour-package':           { label: 'Ladakh Tour Package (6N)',            priceINR: 22999, originalPriceINR: 29999 },
  'spiti-valley-tour-package':     { label: 'Spiti Valley Tour Package (7N)',      priceINR: 19999, originalPriceINR: 25999 },
  'europe-tour-package-from-india':{ label: 'Europe Tour Package from India (10N)',priceINR: 124999,originalPriceINR: 159999},
  'vietnam-tour-package':          { label: 'Vietnam Tour Package (6N)',           priceINR: 38999, originalPriceINR: 49999 },
  'sri-lanka-tour-package':        { label: 'Sri Lanka Tour Package (5N)',         priceINR: 28999, originalPriceINR: 37999 },
  'nepal-tour-package':            { label: 'Nepal Tour Package (5N)',             priceINR: 18999, originalPriceINR: 24999 },
};
